language: node_js
node_js:
  - lts/*

after_success:
  - rm -rf .git
  - git clone https://github.com/BrianLinggadjaja/mynameisbrian.dev-Public.git
  - mv mynameisbrian.dev-Public/.git dist/
  - cd dist
  - git remote rm origin
  - git remote add origin https://username:${GH_TOKEN}@github.com/BrianLinggadjaja/mynameisbrian.dev-Public
  - git add .
  - git commit -m "Travis-CI automated build"
  - git push -fq origin ${GIT_BRANCH}
