# This is a basic workflow to help you get started with Actions
name: Build Repo

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: main

      # Display Directory
      - name: Display directory listing
        run: ls -all

      # Runs a single command using the runners shell
      - name: Install dependencies
        run: npm install

      # Compiles repository under src/.vuepress/dist
      - name: Compile code
        run: npm run build

      # Test
      - name: Add compiled code
        run: |
          git status
          git add .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "Auto generated code"

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: prod

      # Test
      - name: Add compiled code
        run: |
          git rebase main
          git push
